name: CI Tests

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches:
      - 'main'
jobs:
  linux:
    name: Test on OTP ${{ matrix.otp_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp_version: ['26.0', '25.3', '24.3']
        rebar3: ['3.22.0']
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Erlang
      uses: erlef/setup-beam@v1
      id: setup-beam
      with:
        otp-version: ${{matrix.otp_version}}
        rebar3-version: ${{matrix.rebar3}}
    - name: Restore Dialyzer PLT
      uses: actions/cache@v3
      with:
        path: _build/*/rebar3_*_plt
        key: dialyzer-plt-cache-${{ steps.setup-beam.outputs.otp-version }}-${{ runner.os }}-${{ hashFiles('rebar.config*') }}-v1
    - name: Compile
      run: rebar3 compile
    - name: Xref
      run: rebar3 xref
    - name: EUnit (unit tests)
      run: rebar3 eunit --verbose --cover
    - name: Dialyzer
      run: rebar3 dialyzer

